# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gmoindro <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/03 16:19:31 by gmoindro          #+#    #+#              #
#    Updated: 2019/04/03 16:19:54 by gmoindro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file

SRCS=srcs/*.c

all:
		gcc $(SRCS) -o $(NAME)

clean:
		/bin/rm -f *.o

fclean: clean
		/bin/rm -f $(NAME)

re: fclean re
